# Generated by Django 3.2.9 on 2026-02-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicKuGou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(default='aaa', max_length=50, verbose_name='是否启用')),
                ('sing_title', models.CharField(default='aaa', max_length=50, verbose_name='歌名')),
                ('singer', models.CharField(default='aaa', max_length=50, verbose_name='歌手')),
                ('format_sing_title', models.CharField(default='aaa', max_length=50, verbose_name='格式化后的歌名')),
                ('format_singer', models.CharField(default='aaa', max_length=50, verbose_name='格式化后的歌手')),
                ('name', models.CharField(default='aaa', max_length=100, verbose_name='歌曲完整信息')),
                ('playLink', models.URLField(default='http://49.234.15.210/static/web/articles/cover.jpg', max_length=100, verbose_name='播放地址')),
                ('downloadUrl', models.URLField(default='http://49.234.15.210/static/web/articles/cover.jpg', max_length=100, verbose_name='下载地址')),
                ('originDownloadUrl', models.URLField(default='http://49.234.15.210/static/web/articles/cover.jpg', max_length=240, verbose_name='原下载地址')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='上传日期')),
                ('dateCreatedStr', models.CharField(default='2023-02-27 00:00:00', max_length=50, verbose_name='上传日期(年月日时分秒)')),
            ],
            options={
                'db_table': 'app_music_v1s',
            },
        ),
        migrations.CreateModel(
            name='RequestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(default='aaa', max_length=50, verbose_name='路径')),
                ('query_string', models.CharField(default='', max_length=1000, verbose_name='查询字符串')),
                ('get_or_post_param', models.CharField(default='', max_length=1000, verbose_name='get or post参数')),
                ('ip', models.CharField(default='aaa', max_length=50, verbose_name='ip')),
                ('continent', models.CharField(default='aaa', max_length=240, verbose_name='大洲')),
                ('country_code', models.CharField(default='aaa', max_length=240, verbose_name='国家或地区代码')),
                ('country_name', models.CharField(default='aaa', max_length=240, verbose_name='国家或地区名称')),
                ('area_name', models.CharField(default='aaa', max_length=240, verbose_name='地区名称')),
                ('city_name', models.CharField(default='aaa', max_length=240, verbose_name='城市名称')),
                ('city_latitude', models.CharField(default='aaa', max_length=50, verbose_name='城市纬度')),
                ('city_longitude', models.CharField(default='aaa', max_length=50, verbose_name='城市经度')),
                ('service_provider', models.CharField(default='aaa', max_length=240, verbose_name='服务商')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('dateCreatedStr', models.CharField(default='2023-02-27 00:00:00', max_length=50, verbose_name='创建日期(年月日时分秒)')),
            ],
            options={
                'db_table': 'app_request_infos',
            },
        ),
    ]
