# Generated by Django 3.2.9 on 2026-02-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('url', models.CharField(max_length=50, verbose_name='播放地址')),
                ('pic', models.CharField(max_length=50, verbose_name='封面图片')),
                ('lrc', models.TextField(verbose_name='歌词')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='上传日期')),
            ],
            options={
                'db_table': 'app_interface_music_player',
            },
        ),
        migrations.AlterModelTable(
            name='musickugou',
            table='app_interface_music_v1s',
        ),
        migrations.AlterModelTable(
            name='requestinfo',
            table='app_interface_request_infos',
        ),
    ]
