# Generated by Django 3.2.9 on 2026-02-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20260204_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicplayer',
            name='pic',
            field=models.CharField(max_length=200, verbose_name='封面图片'),
        ),
    ]
