# Generated by Django 3.2.9 on 2026-02-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=20, verbose_name='应用')),
                ('method', models.CharField(max_length=20, verbose_name='请求方法')),
                ('url', models.URLField(default='http://49.234.15.210/', verbose_name='请求地址')),
                ('description', models.CharField(max_length=240, verbose_name='请求描述')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('dateUpdate', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('dateCreatedStr', models.CharField(default='2023-02-27 00:00:00', max_length=50, verbose_name='创建日期(年月日时分秒)')),
            ],
            options={
                'db_table': 'app_apis',
            },
        ),
    ]
