# Generated by Django 3.2.9 on 2026-02-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media', verbose_name='服务器文件')),
                ('downloadLink', models.URLField(default='http://49.234.15.210/static/web/articles/cover.jpg', max_length=100, verbose_name='下载地址')),
                ('origin', models.CharField(default='aaa', max_length=50, verbose_name='原文件全称')),
                ('originalName', models.CharField(default='aaa', max_length=50, verbose_name='原文件名称')),
                ('originalType', models.CharField(default='txt', max_length=20, verbose_name='原文件类型')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='上传日期')),
                ('dateCreatedStr', models.CharField(default='2022-06-14 00:00:00', max_length=50, verbose_name='上传日期(年月日时分秒)')),
            ],
            options={
                'db_table': 'app_documents',
            },
        ),
    ]
