"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from custom import Constant

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c*137!ddzi1wr3wraiz)w8pps@_i257u=54#jv3u)6bf$kgn)9'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True  # 调试模式

ALLOWED_HOSTS = ['*']  # 修改允许所有用户访问

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',  # 需要使用其内部封装完成度高的类
    'django_filters',  # 过滤器
    'rest_framework.authtoken',  # 认证限流

    'account',  # 账户应用
    'article',  # 文章列表应用
    'document',  # 上传附件应用
    'book',  # 阅读书籍应用
    'summary',  # 摘要应用
    'api',  # 记录系统所有接口的应用
    'interface',  # 其他接口应用

    'corsheaders',  # 解决django后端跨域问题
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # 防止跨站请求伪造的功能
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'corsheaders.middleware.CorsMiddleware',  # 解决django后端跨域问题
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'others/static')],  # 配置vue项目  frontend  others/static
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'kaede',
        'USER': 'root',
        'PASSWORD': 'Ping.1235',
        'HOST': 'localhost',
        'PORT': 3306,
        'OPTIONS': {'charset': 'utf8mb4'}
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'


USE_I18N = True

USE_L10N = True

# USE_TZ = True

# 解决时区问题 Django admin展示以及数据库实际存储
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 添加内容

# 生成Django接口自带的静态文件,步骤如下
# 1.首先在settings.py文件下定义 STATIC_ROOT = os.path.join(BASE_DIR, "collected_static")
# 2.使用命令 python manage.py collectstatic
# 原理:他会在BASE_DIR目录(默认目录就是进入Django项目里面的第一级)下生成名叫collected_static的文件,
# 里面的内容就是自带的Django接口的静态文件,后面建议统一使用 STATICFILES_DIRS 去包含静态文件路径,因为它可以
# 定义包含多个静态文件路径,就不要使用 STATIC_ROOT
# 注意:Django自带的静态文件在本地不需要使用，但是部署后就需要使用其生成的静态文件

# 调试模式
# DEBUG = True

# 1.只使用Django接口自带的静态文件
# 注意:要使用Django接口自带的静态文件,必须修改 STATIC_URL为其他值,不能是原值(/static/)
# STATIC_URL = '/web/'  # STATIC_URL 修改为任意其他值
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "collected_static"),  # 当前条件下可以不用写这部分
# ]

# 2.使用Django接口自带的静态文件+服务器部署的静态文件供客户端使用的静态文件
# 注意:web/static就是开放给客户端访问的静态资源目录，客户端要访问该目录下的静态文件，直接使用 STATIC_URL(web)即可
# 例如: ~/web/img/1.jpg 客户端通过 STATIC_URL(这里就是url里的web) 访问Django项目下的web/static/img/1.jpg文件
# STATIC_URL = '/web/'  # STATIC_URL 修改为任意其他值
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "collected_static"),  # Django接口自带的静态文件路径
#     os.path.join(BASE_DIR, "web/static"),  # 开放给客户端的静态资源目录
# ]

# 3.使用Django接口自带的静态文件+服务器部署的静态文件供客户端使用的静态文件+模板文件(Vue项目、404页面)
# 注意:要使用Vue项目，还需要在 TEMPLATES下,DIRS里填入 os.path.join(BASE_DIR, 'frontend') 内容,
# BASE_DIR表示Django项目目录第一级,整个含义表示将Django项目下的frontend文件目录放入模板中,
# 就可以访问里面的html,一般放的是Vue打包后生成的项目文件,即将Vue打包的整个文件放入frontend里面
# Vue部署后要访问静态资源是通过 vue.config.js的assetsDir去找所有静态资源,而Django是通过STATIC_URL去访问静态资源,
# 因此它们两个里面的内容要相同,然后Django配置Vue的静态资源时,定位到Vue打包生成的静态文件即可
# STATIC_URL = '/web/'  # STATIC_URL 修改为任意其他值,与Vue项目的 vue.config.js的assetsDir相同
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "others/static"),  # Django接口自带的静态文件路径
#     os.path.join(BASE_DIR, "others/static/web"),  # 开放给客户端的静态资源目录
#     os.path.join(BASE_DIR, 'others/static'),  # Vue项目打包生成的静态文件目录
# ]

# 非调试模式下
# DEBUG = False

# 注:DEBUG=False,则表示生产环境,Django项目一旦用于生产环境,则静态文件路由就不应该由Django去走了,需要第三方去配置,
# 比如Nginx;另外就是404页面也需要在非调试模式下,因为调试模式404是具体的错误信息,方便开发人员去查找处理错误信息
# Nginx设置静态文件从 alias下面寻找,所有的静态文件都放在该目录下面
# location /static/ {
#         alias /home/server/others/static/;
#         expires max;
#         access_log        off;
#         log_not_found     off;
#     }

# 1.只使用Django接口自带的静态文件
# 注意:非调试模式 STATIC_URL保持原来的值
# STATIC_URL = '/static/'

# 2.使用Django接口自带的静态文件+服务器部署的静态文件供客户端使用的静态文件
# 注意:开发的静态资源文件都放在Nginx配置的静态目录下即可
# 通过 STATIC_URL(static)访问开放给客户端的静态文件
# 例如:~/static/img/1.jpg 通过static直接访问Nginx配置的静态目录下的img文件下的1.jpg文件

# 3.使用Django接口自带的静态文件+服务器部署的静态文件供客户端使用的静态文件+模板文件(Vue项目、404页面)
# 注意:将Vue打包生成的项目放在Nginx配置的静态目录下即可,同时需要重新定义TEMPLATES下的DIRS
# 改为 os.path.join(BASE_DIR, 'others/static'),~/others/static下面为Vue项目和404等html.以及所有的静态资源


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (  # 认证类
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': (  # 指定限流类
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {  # 限流措施
        'anon': '1000/day',
        'user': '100000/day'
    },
    'DEFAULT_PAGINATION_CLASS': 'pagination.PageNumberPaginationManual',  # 分页
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',  # 配置自动生成接口文档的默认配置
    'DEFAULT_VERSION': 'v1',  # 默认版本
    'ALLOWED_VERSIONS': ['v1', 'v2'],  # 允许的版本
    'VERSION_PARAM': 'version'  # URL中获取值的key
}

CORS_ORIGIN_ALLOW_ALL = True  # 解决django后端跨域问题

# 上传文件的配置
MEDIA_URL = '/others/document/'  # 与下面的 MEDIA_ROOT里面的值除了多两个/外，其它都要一样
MEDIA_ROOT = os.path.join(BASE_DIR, 'others/document')  # others/document文件是上传文件的根目录

# 下面是需要用到的常量，可能需要根据不同的环境以及情况来测试，方便管理
constant = Constant()

# 生成静态文件打开
# STATIC_ROOT = os.path.join(BASE_DIR, "django-static")
# 1.是否调试模式
DEBUG = constant.settings_debug
if DEBUG is True:
    # 调试模式
    STATIC_URL = '/django-static/'  # STATIC_URL 修改为任意其他值,与Vue项目的 vue.config.js的assetsDir相同
    STATICFILES_DIRS = [
        # os.path.join(BASE_DIR, "others/static"),  # Django接口自带的静态文件路径
        os.path.join(BASE_DIR, "django-static/web"),  # 开放给客户端的静态资源目录
        # os.path.join(BASE_DIR, 'others/static'),  # Vue项目打包生成的静态文件目录
    ]
else:
    # 非调试模式
    STATIC_URL = '/django-static/'
