# Generated by Django 3.2.9 on 2026-02-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('author', models.CharField(default=None, max_length=50)),
                ('summary', models.CharField(max_length=2000)),
                ('date', models.DateField(default=None)),
            ],
            options={
                'db_table': 'app_summaries',
            },
        ),
    ]
