# Generated by Django 3.2.9 on 2026-02-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('last_up_date', models.DateField(default=None)),
                ('cover_url', models.URLField(default='https://i2.hdslb.com/bfs/face/2c28f8d11c0bd7920cd585976c0c61b7f9143c32.jpg')),
                ('address', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'app_articles',
            },
        ),
    ]
