# Generated by Django 3.2.9 on 2026-02-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover', models.URLField(default='http://49.234.15.210/static/web/articles/cover.jpg')),
                ('author', models.CharField(max_length=40)),
                ('nationality', models.CharField(max_length=20)),
                ('translator', models.CharField(max_length=20)),
                ('startingTime', models.DateField(default=None)),
                ('endTime', models.DateField(default=None)),
                ('summary', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'app_books',
            },
        ),
    ]
